### ISSUE TITLE
Question--what is the underlying planner used by default?

### ISSUE THREAD

**Issue by ddevleena** [AI-Planning/cloud-solver#7]
Hi, I've been trying to figure out what the underlying planner is behind planning.domains. I know with plan-utils we can switch out the planner with other planners. But by default what type of planner is planning.domains running? Is it a version of Fast Downward? Fast Forward? 

Thanks! I appreciate it!

**Comment by haz** [comment]
Version of https://lapkt-dev.github.io/docs/

This is the one: https://github.com/AI-Planning/cloud-solver/blob/master/siw-then-bfsf
